# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CP4.ui'
#
# Created: Thu May  8 10:59:57 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!
# Updated: Wednesday Sep 8 2020
#  by: Vera Worri
#  Updated to PyQt5

from PyQt5 import QtWidgets, QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(734, 533)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_3.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_3.addWidget(self.label_19)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mr = QtWidgets.QDoubleSpinBox(Dialog)
        self.mr.setDecimals(10)
        self.mr.setMaximum(999999999.0)
        self.mr.setObjectName(_fromUtf8("mr"))
        self.verticalLayout_2.addWidget(self.mr)
        self.l = QtWidgets.QDoubleSpinBox(Dialog)
        self.l.setDecimals(10)
        self.l.setMaximum(999999999.99)
        self.l.setObjectName(_fromUtf8("l"))
        self.verticalLayout_2.addWidget(self.l)
        self.md = QtWidgets.QDoubleSpinBox(Dialog)
        self.md.setDecimals(10)
        self.md.setMaximum(999999999.99)
        self.md.setObjectName(_fromUtf8("md"))
        self.verticalLayout_2.addWidget(self.md)
        self.r = QtWidgets.QDoubleSpinBox(Dialog)
        self.r.setDecimals(10)
        self.r.setMaximum(999999999.99)
        self.r.setObjectName(_fromUtf8("r"))
        self.verticalLayout_2.addWidget(self.r)
        self.Res = QtWidgets.QDoubleSpinBox(Dialog)
        self.Res.setDecimals(10)
        self.Res.setMaximum(999999999.99)
        self.Res.setObjectName(_fromUtf8("Res"))
        self.verticalLayout_2.addWidget(self.Res)
        self.Da = QtWidgets.QDoubleSpinBox(Dialog)
        self.Da.setDecimals(10)
        self.Da.setMaximum(999999999.99)
        self.Da.setObjectName(_fromUtf8("Da"))
        self.verticalLayout_2.addWidget(self.Da)
        self.Dr = QtWidgets.QDoubleSpinBox(Dialog)
        self.Dr.setDecimals(10)
        self.Dr.setMaximum(999999999.99)
        self.Dr.setObjectName(_fromUtf8("Dr"))
        self.verticalLayout_2.addWidget(self.Dr)
        self.MagField = QtWidgets.QDoubleSpinBox(Dialog)
        self.MagField.setDecimals(10)
        self.MagField.setObjectName(_fromUtf8("doubleSpinBox"))
        self.verticalLayout_2.addWidget(self.MagField)
        self.t = QtWidgets.QDoubleSpinBox(Dialog)
        self.t.setDecimals(10)
        self.t.setObjectName(_fromUtf8("t"))
        self.verticalLayout_2.addWidget(self.t)
        self.omegaD = QtWidgets.QDoubleSpinBox(Dialog)
        self.omegaD.setDecimals(10)
        self.omegaD.setObjectName(_fromUtf8("t_2"))
        self.verticalLayout_2.addWidget(self.omegaD)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout.addWidget(self.label_16)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout.addWidget(self.label_18)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout.addWidget(self.label_20)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_4.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label.setText(_translate("Dialog", "Pendulum Mass", None))
        self.label_2.setText(_translate("Dialog", "Pendulum Arm Length", None))
        self.label_3.setText(_translate("Dialog", "Disk Mass", None))
        self.label_4.setText(_translate("Dialog", "Disk Radius", None))
        self.label_5.setText(_translate("Dialog", "Resistivity of Disk Metal", None))
        self.label_6.setText(_translate("Dialog", "Dampening Coefficient", None))
        self.label_7.setText(_translate("Dialog", "Driving Coefficient", None))
        self.label_10.setText(_translate("Dialog", "External Magnetic Field", None))
        self.label_17.setText(_translate("Dialog", "Time Step", None))
        self.label_19.setText(_translate("Dialog", "Driving Frequency", None))
        self.label_8.setText(_translate("Dialog", "Kilograms", None))
        self.label_9.setText(_translate("Dialog", "Meters", None))
        self.label_11.setText(_translate("Dialog", "Kilograms", None))
        self.label_12.setText(_translate("Dialog", "Meters", None))
        self.label_13.setText(_translate("Dialog", "Oms Meters", None))
        self.label_14.setText(_translate("Dialog", "unitless", None))
        self.label_15.setText(_translate("Dialog", "unitless", None))
        self.label_16.setText(_translate("Dialog", "Teslas", None))
        self.label_18.setText(_translate("Dialog", "seconds", None))
        self.label_20.setText(_translate("Dialog", "Hertz", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

